export type WorksheetCatalogItem = {
  code: string;
  full: string;
  label: string;
};

export const WORKSHEET_OUTCOME_CATALOG: Record<number, WorksheetCatalogItem[]> = {
  5: [
    { code: 'MAT.5.3.1.', label: 'Temel geometrik çizimler için matematiksel araç ve teknolojiden yararlanabilme', full: 'MAT.5.3.1. Temel geometrik çizimler için matematiksel araç ve teknolojiden yararlanabilme' },
    { code: 'MAT.5.3.2.', label: 'Temel geometrik çizimlere dayalı deneyimlerini yansıtabilme', full: 'MAT.5.3.2. Temel geometrik çizimlere dayalı deneyimlerini yansıtabilme' },
    { code: 'MAT.5.3.3.', label: 'Açıları ölçmek için matematiksel araç ve teknolojiden yararlanabilme', full: 'MAT.5.3.3. Açıları ölçmek için matematiksel araç ve teknolojiden yararlanabilme' },
    { code: 'MAT.5.3.4.', label: 'Düzlemde iki veya üç doğrunun birbirine göre durumuna bağlı olarak oluşabilecek açılara dair çıkarım yapabilme', full: 'MAT.5.3.4. Düzlemde iki veya üç doğrunun birbirine göre durumuna bağlı olarak oluşabilecek açılara dair çıkarım yapabilme' },
    { code: 'MAT.5.3.5.', label: 'Çokgenleri düzlemde ardışık olarak kesişen doğruların oluşturduğu kapalı şekiller olarak yorumlayabilme', full: 'MAT.5.3.5. Çokgenleri düzlemde ardışık olarak kesişen doğruların oluşturduğu kapalı şekiller olarak yorumlayabilme' },
    { code: 'MAT.5.3.6.', label: 'Çokgenlerin özellikleri ile ilgili edindiği deneyimleri yansıtabilme', full: 'MAT.5.3.6. Çokgenlerin özellikleri ile ilgili edindiği deneyimleri yansıtabilme' },
    { code: 'MAT.5.3.7.', label: 'Matematiksel araç ve teknoloji yardımıyla düzlemde iki noktada kesişen çember çiftinin merkezleri ve kesişim noktalarından biri ile inşa edilen üçgenlerin kenar özelliklerine yönelik muhakeme yapabilme', full: 'MAT.5.3.7. Matematiksel araç ve teknoloji yardımıyla düzlemde iki noktada kesişen çember çiftinin merkezleri ve kesişim noktalarından biri ile inşa edilen üçgenlerin kenar özelliklerine yönelik muhakeme yapabilme' },
    { code: 'MAT.5.1.1.', label: 'Altı basamaklı sayıları okuma ve yazmayı çok basamaklı sayılara genelleyebilme', full: 'MAT.5.1.1. Altı basamaklı sayıları okuma ve yazmayı çok basamaklı sayılara genelleyebilme' },
    { code: 'MAT.5.1.2.', label: 'Doğal sayılar ve işlemler içeren gerçek yaşam problemlerini çözebilme', full: 'MAT.5.1.2. Doğal sayılar ve işlemler içeren gerçek yaşam problemlerini çözebilme' },
    { code: 'MAT.5.4.1.', label: 'Kenar uzunlukları doğal sayı olan bir dikdörtgenin çevre uzunluğu verildiğinde kenar uzunluklarını yorumlayabilme', full: 'MAT.5.4.1. Kenar uzunlukları doğal sayı olan bir dikdörtgenin çevre uzunluğu verildiğinde kenar uzunluklarını yorumlayabilme' },
    { code: 'MAT.5.4.2.', label: 'Birim karelerden yola çıkarak bir şeklin alanını değerlendirebilme', full: 'MAT.5.4.2. Birim karelerden yola çıkarak bir şeklin alanını değerlendirebilme' },
    { code: 'MAT.5.4.3.', label: 'Kenar uzunlukları doğal sayı olan bir dikdörtgenin alanının ölçüsü verildiğinde çevre uzunluğunu, çevre uzunluğu verildiğinde alanını yorumlayabilme', full: 'MAT.5.4.3. Kenar uzunlukları doğal sayı olan bir dikdörtgenin alanının ölçüsü verildiğinde çevre uzunluğunu, çevre uzunluğu verildiğinde alanını yorumlayabilme' },
    { code: 'MAT.5.4.4.', label: 'Dikdörtgenin çevre uzunluğu ve alanı ile ilgili problemleri çözebilme', full: 'MAT.5.4.4. Dikdörtgenin çevre uzunluğu ve alanı ile ilgili problemleri çözebilme' },
    { code: 'MAT.5.1.3.', label: 'Gerçek yaşam durumlarına karşılık gelen kesirleri farklı biçimlerde temsil edebilme', full: 'MAT.5.1.3. Gerçek yaşam durumlarına karşılık gelen kesirleri farklı biçimlerde temsil edebilme' },
    { code: 'MAT.5.1.4.', label: 'Farklı gösterimlerle ifade edilen kesirlerin karşılaştırılmasına yönelik çıkarım yapabilme', full: 'MAT.5.1.4. Farklı gösterimlerle ifade edilen kesirlerin karşılaştırılmasına yönelik çıkarım yapabilme' },
    { code: 'MAT.5.5.1.', label: 'Kategorik veri ile çalışabilme ve veriye dayalı karar verebilme', full: 'MAT.5.5.1. Kategorik veri ile çalışabilme ve veriye dayalı karar verebilme' },
    { code: 'MAT.5.5.2.', label: 'Başkaları tarafından oluşturulan kategorik veriye dayalı istatistiksel sonuç veya yorumları tartışabilme', full: 'MAT.5.5.2. Başkaları tarafından oluşturulan kategorik veriye dayalı istatistiksel sonuç veya yorumları tartışabilme' },
    { code: 'MAT.5.2.1.', label: 'Eşitliğin korunumuna ve işlem özelliklerine yönelik çıkarım yapabilme', full: 'MAT.5.2.1. Eşitliğin korunumuna ve işlem özelliklerine yönelik çıkarım yapabilme' },
    { code: 'MAT.5.2.2.', label: 'Karşılaştığı günlük hayat ya da matematiksel durumlarda işlem önceliğini yorumlayabilme', full: 'MAT.5.2.2. Karşılaştığı günlük hayat ya da matematiksel durumlarda işlem önceliğini yorumlayabilme' },
    { code: 'MAT.5.2.3.', label: 'Sayı ve şekil örüntülerinin kuralına ilişkin muhakeme yapabilme', full: 'MAT.5.2.3. Sayı ve şekil örüntülerinin kuralına ilişkin muhakeme yapabilme' },
    { code: 'MAT.5.2.4.', label: 'Temel aritmetik işlem içeren durumlardaki algoritmaları yorumlayabilme', full: 'MAT.5.2.4. Temel aritmetik işlem içeren durumlardaki algoritmaları yorumlayabilme' },
    { code: 'MAT.5.6.1.', label: 'Herhangi bir olayın olasılığının 0 (imkânsız) ile 1 (kesin) arasında (0 ve 1 dâhil)', full: 'MAT.5.6.1. Herhangi bir olayın olasılığının 0 (imkânsız) ile 1 (kesin) arasında (0 ve 1 dâhil)' },
    { code: 'MAT.5.6.2.', label: 'Olayları az ya da çok olasılıklı şeklinde yapılandırabilme', full: 'MAT.5.6.2. Olayları az ya da çok olasılıklı şeklinde yapılandırabilme' },
  ],
  6: [
    { code: 'MAT.6.1.1.', label: 'Karşılaştığı problem durumlarında bir doğal sayının çarpan ve katlarına yönelik muhakeme yapabilme', full: 'MAT.6.1.1. Karşılaştığı problem durumlarında bir doğal sayının çarpan ve katlarına yönelik muhakeme yapabilme' },
    { code: 'MAT.6.1.2.', label: 'Bir doğal sayının 2, 3, 4, 5, 6, 9 ve 10 ile tam bölünebilme kriterlerine ilişkin çıkarım yapabilme', full: 'MAT.6.1.2. Bir doğal sayının 2, 3, 4, 5, 6, 9 ve 10 ile tam bölünebilme kriterlerine ilişkin çıkarım yapabilme' },
    { code: 'MAT.6.1.3.', label: 'Bir doğal sayının asal olma durumunu ve asal çarpanlarını çözümleyebilme', full: 'MAT.6.1.3. Bir doğal sayının asal olma durumunu ve asal çarpanlarını çözümleyebilme' },
    { code: 'MAT.6.1.4.', label: 'Günlük hayat problemleri ya da matematiksel durumlar üzerinden ortak kat ve ortak böleni yorumlayabilme', full: 'MAT.6.1.4. Günlük hayat problemleri ya da matematiksel durumlar üzerinden ortak kat ve ortak böleni yorumlayabilme' },
    { code: 'MAT.6.5.1.', label: 'Kategorik veya nicel (kesikli) veri ile çalışabilme ve veriye dayalı karar verebilme', full: 'MAT.6.5.1. Kategorik veya nicel (kesikli) veri ile çalışabilme ve veriye dayalı karar verebilme' },
    { code: 'MAT.6.5.2.', label: 'Başkaları tarafından oluşturulan kategorik veya nicel (kesikli) veriye dayalı istatistiksel sonuç veya yorumları tartışabilme', full: 'MAT.6.5.2. Başkaları tarafından oluşturulan kategorik veya nicel (kesikli) veriye dayalı istatistiksel sonuç veya yorumları tartışabilme' },
    { code: 'MAT.6.1.5.', label: 'Gerçek yaşam durumlarında ondalık gösterimlerin basamak değerlerini kesirlerden yararlanarak yorumlayabilme', full: 'MAT.6.1.5. Gerçek yaşam durumlarında ondalık gösterimlerin basamak değerlerini kesirlerden yararlanarak yorumlayabilme' },
    { code: 'MAT.6.1.6.', label: 'Kesir ve bölme işlemi arasındaki ilişkiye yönelik tümevarımsal akıl yürütebilme', full: 'MAT.6.1.6. Kesir ve bölme işlemi arasındaki ilişkiye yönelik tümevarımsal akıl yürütebilme' },
    { code: 'MAT.6.1.7.', label: 'Karşılaştığı günlük hayat ya da matematiksel durumlarda standart uzunluk ölçme birimlerini değerlendirebilme', full: 'MAT.6.1.7. Karşılaştığı günlük hayat ya da matematiksel durumlarda standart uzunluk ölçme birimlerini değerlendirebilme' },
    { code: 'MAT.6.1.8.', label: 'Gerçek yaşam durumlarında karşılaşılan kesir, ondalık ve yüzde gösterimleri ile ilgili dört işlem gerektiren problemleri çözebilme', full: 'MAT.6.1.8. Gerçek yaşam durumlarında karşılaşılan kesir, ondalık ve yüzde gösterimleri ile ilgili dört işlem gerektiren problemleri çözebilme' },
    { code: 'MAT.6.6.1.', label: 'Bir olayın olasılığını gözleme dayalı tahmin edebilme', full: 'MAT.6.6.1. Bir olayın olasılığını gözleme dayalı tahmin edebilme' },
    { code: 'MAT.6.3.1.', label: 'Düzlemde iki paralel doğru ve bir kesen ile oluşan açıları sınıflandırabilme', full: 'MAT.6.3.1. Düzlemde iki paralel doğru ve bir kesen ile oluşan açıları sınıflandırabilme' },
    { code: 'MAT.6.3.2.', label: 'Matematiksel araç ve teknolojiden yararlanarak iki paralel doğrunun iki kesenle oluşturduğu şekillerin özelliklerine dair çıkarım yapabilme', full: 'MAT.6.3.2. Matematiksel araç ve teknolojiden yararlanarak iki paralel doğrunun iki kesenle oluşturduğu şekillerin özelliklerine dair çıkarım yapabilme' },
    { code: 'MAT.6.3.3.', label: 'Matematiksel araç ve teknolojiden yararlanarak birbirlerini ortalayan doğru parçalarını köşegen kabul eden dörtgenlere yönelik çıkarım yapabilme', full: 'MAT.6.3.3. Matematiksel araç ve teknolojiden yararlanarak birbirlerini ortalayan doğru parçalarını köşegen kabul eden dörtgenlere yönelik çıkarım yapabilme' },
    { code: 'MAT.6.3.4.', label: 'Üçgen, yamuk, paralelkenar, eşkenar dörtgen, dikdörtgen ve karenin açıları ile ilgili problemleri çözebilme', full: 'MAT.6.3.4. Üçgen, yamuk, paralelkenar, eşkenar dörtgen, dikdörtgen ve karenin açıları ile ilgili problemleri çözebilme' },
    { code: 'MAT.6.2.1.', label: 'Gerçek yaşam durumlarında bilinen niceliklerden bilinmeyen niceliklere ilişkin muhakeme yapabilme', full: 'MAT.6.2.1. Gerçek yaşam durumlarında bilinen niceliklerden bilinmeyen niceliklere ilişkin muhakeme yapabilme' },
    { code: 'MAT.6.2.2.', label: 'Sayı ve şekil örüntülerini yorumlayabilme', full: 'MAT.6.2.2. Sayı ve şekil örüntülerini yorumlayabilme' },
    { code: 'MAT.6.2.3.', label: 'Cebirsel ifadeler içeren durumlardaki algoritmaları yorumlayabilme', full: 'MAT.6.2.3. Cebirsel ifadeler içeren durumlardaki algoritmaları yorumlayabilme' },
    { code: 'MAT.6.4.1.', label: 'Uzunluk ve alan ölçme birimleri arasındaki ilişkilerle ilgili analojik akıl yürütebilme', full: 'MAT.6.4.1. Uzunluk ve alan ölçme birimleri arasındaki ilişkilerle ilgili analojik akıl yürütebilme' },
    { code: 'MAT.6.4.2.', label: 'Dikdörtgenin alan bağıntısına yönelik deneyimlerini paralelkenar ve üçgenin alan bağıntılarına yansıtabilme', full: 'MAT.6.4.2. Dikdörtgenin alan bağıntısına yönelik deneyimlerini paralelkenar ve üçgenin alan bağıntılarına yansıtabilme' },
    { code: 'MAT.6.4.3.', label: 'Geometrik şekillerin alanları ile modellenen gerçek yaşam durumlarına yönelik problem çözebilme', full: 'MAT.6.4.3. Geometrik şekillerin alanları ile modellenen gerçek yaşam durumlarına yönelik problem çözebilme' },
    { code: 'MAT.6.4.4.', label: 'Çemberin uzunluğu ile çap uzunluğu arasındaki ilişkiye yönelik çıkarım yapabilme', full: 'MAT.6.4.4. Çemberin uzunluğu ile çap uzunluğu arasındaki ilişkiye yönelik çıkarım yapabilme' },
    { code: 'MAT.6.4.5.', label: 'Çap veya yarıçap uzunluğu verilen bir çemberin uzunluğu ile ilgili problemleri çözebilme', full: 'MAT.6.4.5. Çap veya yarıçap uzunluğu verilen bir çemberin uzunluğu ile ilgili problemleri çözebilme' },
  ],
  7: [
    { code: 'M.7.1.1.1.', label: 'Tam sayılarla toplama ve çıkarma işlemlerini yapar, ilgili problemleri çözer', full: 'M.7.1.1.1. Tam sayılarla toplama ve çıkarma işlemlerini yapar, ilgili problemleri çözer.' },
    { code: 'M.7.1.1.2.', label: 'Toplama işleminin özelliklerini akıcı işlem yapmak için birer strateji olarak kullanır', full: 'M.7.1.1.2. Toplama işleminin özelliklerini akıcı işlem yapmak için birer strateji olarak kullanır.' },
    { code: 'M.7.1.1.3.', label: 'Tam sayılarla çarpma ve bölme işlemlerini yapar', full: 'M.7.1.1.3. Tam sayılarla çarpma ve bölme işlemlerini yapar.' },
    { code: 'M.7.1.1.4.', label: 'Tam sayıların kendileri ile tekrarlı çarpımını üslü nicelik olarak ifade eder', full: 'M.7.1.1.4. Tam sayıların kendileri ile tekrarlı çarpımını üslü nicelik olarak ifade eder.' },
    { code: 'M.7.1.1.5.', label: 'Tam sayılarla işlemler yapmayı gerektiren problemleri çözer', full: 'M.7.1.1.5. Tam sayılarla işlemler yapmayı gerektiren problemleri çözer.' },
    { code: 'M.7.1.2.1.', label: 'Rasyonel sayıları tanır ve sayı doğrusunda gösterir', full: 'M.7.1.2.1. Rasyonel sayıları tanır ve sayı doğrusunda gösterir.' },
    { code: 'M.7.1.2.2.', label: 'Rasyonel sayıları ondalık gösterimle ifade eder', full: 'M.7.1.2.2. Rasyonel sayıları ondalık gösterimle ifade eder.' },
    { code: 'M.7.1.2.3.', label: 'Devirli olan ve olmayan ondalık gösterimleri rasyonel sayı olarak ifade eder', full: 'M.7.1.2.3. Devirli olan ve olmayan ondalık gösterimleri rasyonel sayı olarak ifade eder.' },
    { code: 'M.7.1.2.4.', label: 'Rasyonel sayıları sıralar ve karşılaştırır', full: 'M.7.1.2.4. Rasyonel sayıları sıralar ve karşılaştırır.' },
    { code: 'M.7.1.3.1.', label: 'Rasyonel sayılarla toplama ve çıkarma işlemlerini yapar', full: 'M.7.1.3.1. Rasyonel sayılarla toplama ve çıkarma işlemlerini yapar.' },
    { code: 'M.7.1.3.2.', label: 'Rasyonel sayılarla çarpma ve bölme işlemlerini yapar', full: 'M.7.1.3.2. Rasyonel sayılarla çarpma ve bölme işlemlerini yapar.' },
    { code: 'M.7.1.3.3.', label: 'Rasyonel sayılarla çok adımlı işlemleri yapar', full: 'M.7.1.3.3. Rasyonel sayılarla çok adımlı işlemleri yapar.' },
    { code: 'M.7.1.3.4.', label: 'Rasyonel sayıların kare ve küplerini hesaplar', full: 'M.7.1.3.4. Rasyonel sayıların kare ve küplerini hesaplar.' },
    { code: 'M.7.1.3.5.', label: 'Rasyonel sayılarla işlem yapmayı gerektiren problemleri çözer', full: 'M.7.1.3.5. Rasyonel sayılarla işlem yapmayı gerektiren problemleri çözer.' },
    { code: 'M.7.2.1.1.', label: 'Cebirsel ifadelerle toplama ve çıkarma işlemleri yapar', full: 'M.7.2.1.1. Cebirsel ifadelerle toplama ve çıkarma işlemleri yapar.' },
    { code: 'M.7.2.1.2.', label: 'Bir doğal sayı ile bir cebirsel ifadeyi çarpar', full: 'M.7.2.1.2. Bir doğal sayı ile bir cebirsel ifadeyi çarpar.' },
    { code: 'M.7.2.1.3.', label: 'Sayı örüntülerinin kuralını harfle ifade eder, kuralı harfle ifade edilen örüntünün istenilen terimini bulur', full: 'M.7.2.1.3. Sayı örüntülerinin kuralını harfle ifade eder, kuralı harfle ifade edilen örüntünün istenilen terimini bulur.' },
    { code: 'M.7.2.2.1.', label: 'Eşitliğin korunumu ilkesini anlar', full: 'M.7.2.2.1. Eşitliğin korunumu ilkesini anlar.' },
    { code: 'M.7.2.2.2.', label: 'Birinci dereceden bir bilinmeyenli denklemi tanır ve verilen gerçek hayat durumlarına uygun birinci dereceden bir bilinmeyenli denklem kurar', full: 'M.7.2.2.2. Birinci dereceden bir bilinmeyenli denklemi tanır ve verilen gerçek hayat durumlarına uygun birinci dereceden bir bilinmeyenli denklem kurar.' },
    { code: 'M.7.2.2.3.', label: 'Birinci dereceden bir bilinmeyenli denklemleri çözer', full: 'M.7.2.2.3. Birinci dereceden bir bilinmeyenli denklemleri çözer.' },
    { code: 'M.7.2.2.4.', label: 'Birinci dereceden bir bilinmeyenli denklem kurmayı gerektiren problemleri çözer', full: 'M.7.2.2.4. Birinci dereceden bir bilinmeyenli denklem kurmayı gerektiren problemleri çözer.' },
    { code: 'M.7.1.4.1.', label: 'Oranda çokluklardan birinin 1 olması durumunda diğerinin alacağı değeri belirler', full: 'M.7.1.4.1. Oranda çokluklardan birinin 1 olması durumunda diğerinin alacağı değeri belirler.' },
    { code: 'M.7.1.4.2.', label: 'Birbirine oranı verilen iki çokluktan biri verildiğinde diğerini bulur', full: 'M.7.1.4.2. Birbirine oranı verilen iki çokluktan biri verildiğinde diğerini bulur.' },
    { code: 'M.7.1.4.3.', label: 'Gerçek hayat durumlarını inceleyerek iki çokluğun orantılı olup olmadığına karar verir', full: 'M.7.1.4.3. Gerçek hayat durumlarını inceleyerek iki çokluğun orantılı olup olmadığına karar verir.' },
    { code: 'M.7.1.4.4.', label: 'Doğru orantılı iki çokluk arasındaki ilişkiyi ifade eder', full: 'M.7.1.4.4. Doğru orantılı iki çokluk arasındaki ilişkiyi ifade eder.' },
    { code: 'M.7.1.4.5.', label: 'Doğru orantılı iki çokluğa ait orantı sabitini belirler ve yorumlar', full: 'M.7.1.4.5. Doğru orantılı iki çokluğa ait orantı sabitini belirler ve yorumlar.' },
    { code: 'M.7.1.4.6.', label: 'Gerçek hayat durumlarını inceleyerek iki çokluğun ters orantılı olup olmadığına karar verir', full: 'M.7.1.4.6. Gerçek hayat durumlarını inceleyerek iki çokluğun ters orantılı olup olmadığına karar verir.' },
    { code: 'M.7.1.4.7.', label: 'Doğru ve ters orantıyla ilgili problemleri çözer', full: 'M.7.1.4.7. Doğru ve ters orantıyla ilgili problemleri çözer.' },
    { code: 'M.7.1.5.1.', label: 'Bir çokluğun belirtilen bir yüzdesine karşılık gelen miktarını ve belirli bir yüzdesi verilen çokluğun tamamını bulur', full: 'M.7.1.5.1. Bir çokluğun belirtilen bir yüzdesine karşılık gelen miktarını ve belirli bir yüzdesi verilen çokluğun tamamını bulur.' },
    { code: 'M.7.1.5.2.', label: 'Bir çokluğu diğer bir çokluğun yüzdesi olarak hesaplar', full: 'M.7.1.5.2. Bir çokluğu diğer bir çokluğun yüzdesi olarak hesaplar.' },
    { code: 'M.7.1.5.3.', label: 'Bir çokluğu belirli bir yüzde ile arttırmaya veya azaltmaya yönelik hesaplamalar yapar', full: 'M.7.1.5.3. Bir çokluğu belirli bir yüzde ile arttırmaya veya azaltmaya yönelik hesaplamalar yapar.' },
    { code: 'M.7.1.5.4.', label: 'Yüzde ile ilgili problemleri çözer', full: 'M.7.1.5.4. Yüzde ile ilgili problemleri çözer.' },
    { code: 'M.7.3.1.1.', label: 'Bir açıyı iki eş açıya ayırarak açıortayı belirler', full: 'M.7.3.1.1. Bir açıyı iki eş açıya ayırarak açıortayı belirler.' },
    { code: 'M.7.3.1.2.', label: 'İki paralel doğruyla bir keseninin oluşturduğu yöndeş, ters, iç ters, dış ters açıları belirleyerek özelliklerini inceler; oluşan açıların eş veya bütünler olanlarını belirler; ilgili problemleri çözer', full: 'M.7.3.1.2. İki paralel doğruyla bir keseninin oluşturduğu yöndeş, ters, iç ters, dış ters açıları belirleyerek özelliklerini inceler; oluşan açıların eş veya bütünler olanlarını belirler; ilgili problemleri çözer.' },
    { code: 'M.7.3.2.1.', label: 'Düzgün çokgenlerin kenar ve açı özelliklerini açıklar', full: 'M.7.3.2.1. Düzgün çokgenlerin kenar ve açı özelliklerini açıklar.' },
    { code: 'M.7.3.2.2.', label: 'Çokgenlerin köşegenlerini, iç ve dış açılarını belirler; iç açılarının ve dış açılarının ölçüleri toplamını hesaplar', full: 'M.7.3.2.2. Çokgenlerin köşegenlerini, iç ve dış açılarını belirler; iç açılarının ve dış açılarının ölçüleri toplamını hesaplar.' },
    { code: 'M.7.3.2.3.', label: 'Dikdörtgen, paralelkenar, yamuk ve eşkenar dörtgeni tanır; açı özelliklerini belirler', full: 'M.7.3.2.3. Dikdörtgen, paralelkenar, yamuk ve eşkenar dörtgeni tanır; açı özelliklerini belirler.' },
    { code: 'M.7.3.2.4.', label: 'Eşkenar dörtgen ve yamuğun alan bağıntılarını oluşturur, ilgili problemleri çözer', full: 'M.7.3.2.4. Eşkenar dörtgen ve yamuğun alan bağıntılarını oluşturur, ilgili problemleri çözer.' },
    { code: 'M.7.3.2.5.', label: 'Alan ile ilgili problemleri çözer', full: 'M.7.3.2.5. Alan ile ilgili problemleri çözer.' },
    { code: 'M.7.3.3.1.', label: 'Çemberde merkez açıları, gördüğü yayları ve açı ölçüleri arasındaki ilişkileri belirler', full: 'M.7.3.3.1. Çemberde merkez açıları, gördüğü yayları ve açı ölçüleri arasındaki ilişkileri belirler.' },
    { code: 'M.7.3.3.2.', label: 'Çemberin ve çember parçasının uzunluğunu hesaplar', full: 'M.7.3.3.2. Çemberin ve çember parçasının uzunluğunu hesaplar.' },
    { code: 'M.7.3.3.3.', label: 'Dairenin ve daire diliminin alanını hesaplar', full: 'M.7.3.3.3. Dairenin ve daire diliminin alanını hesaplar.' },
    { code: 'M.7.4.1.1.', label: 'Verilere ilişkin çizgi grafiği oluşturur ve yorumlar', full: 'M.7.4.1.1. Verilere ilişkin çizgi grafiği oluşturur ve yorumlar.' },
    { code: 'M.7.4.1.2.', label: 'Bir veri grubuna ait ortalama, ortanca ve tepe değeri bulur ve yorumlar', full: 'M.7.4.1.2. Bir veri grubuna ait ortalama, ortanca ve tepe değeri bulur ve yorumlar.' },
    { code: 'M.7.4.1.3.', label: 'Bir veri grubuna ilişkin daire grafiğini oluşturur ve yorumlar', full: 'M.7.4.1.3. Bir veri grubuna ilişkin daire grafiğini oluşturur ve yorumlar.' },
    { code: 'M.7.4.1.4.', label: 'Verileri sütun, daire veya çizgi grafiği ile gösterir ve bu gösterimler arasında uygun olan dönüşümler yapar', full: 'M.7.4.1.4. Verileri sütun, daire veya çizgi grafiği ile gösterir ve bu gösterimler arasında uygun olan dönüşümleriyapar.' },
    { code: 'M.7.3.4.1.', label: 'Üç boyutlu cisimlerin farklı yönlerden iki boyutlu görünümlerini çizer', full: 'M.7.3.4.1. Üç boyutlu cisimlerin farklı yönlerden iki boyutlu görünümlerini çizer.' },
    { code: 'M.7.3.4.2.', label: 'Farklı yönlerden görünümlerine ilişkin çizimleri verilen yapıları oluşturur', full: 'M.7.3.4.2. Farklı yönlerden görünümlerine ilişkin çizimleri verilen yapıları oluşturur.' },
  ],
  8: [
    { code: 'M.8.1.1.1.', label: 'Verilen pozitif tam sayıların pozitif tam sayı çarpanlarını bulur, pozitif tam sayıların pozitif tam sayı çarpanlarını üslü ifadelerin çarpımı şeklinde yazar', full: 'M.8.1.1.1. Verilen pozitif tam sayıların pozitif tam sayı çarpanlarını bulur, pozitif tam sayıların pozitif tam sayı Çarpanlarını üslü ifadelerin çarpımı şeklinde yazar.' },
    { code: 'M.8.1.1.2.', label: 'İki doğal sayının en büyük ortak bölenini (EBOB) ve en küçük ortak katını (EKOK) hesaplar, ilgili problemleri çözer', full: 'M.8.1.1.2. İki doğal sayının en büyük ortak bölenini (EBOB) ve en küçük ortak katını (EKOK) hesaplar, ilgili problemleri çözer.' },
    { code: 'M.8.1.1.3.', label: 'Verilen iki doğal sayının aralarında asal olup olmadığını belirler', full: 'M.8.1.1.3. Verilen iki doğal sayının aralarında asal olup olmadığını belirler.' },
    { code: 'M.8.1.2.1.', label: 'Tam sayıların, tam sayı kuvvetlerini hesaplar', full: 'M.8.1.2.1.Tam sayıların, tam sayı kuvvetlerini hesaplar.' },
    { code: 'M.8.1.2.2.', label: 'Üslü ifadelerle ilgili temel kuralları anlar, birbirine denk ifadeler oluşturur', full: 'M.8.1.2.2. Üslü ifadelerle ilgili temel kuralları anlar, birbirine denk ifadeler oluşturur.' },
    { code: 'M.8.1.2.3.', label: 'Sayıların ondalık gösterimlerini 10’un tam sayı kuvvetlerini kullanarak çözümler', full: 'M.8.1.2.3. Sayıların ondalık gösterimlerini 10’un tam sayı kuvvetlerini kullanarak çözümler.' },
    { code: 'M.8.1.2.4.', label: 'Verilen bir sayıyı 10’un farklı tam sayı kuvvetlerini kullanarak ifade eder', full: 'M.8.1.2.4. Verilen bir sayıyı 10’un farklı tam sayı kuvvetlerini kullanarak ifade eder.' },
    { code: 'M.8.1.2.5.', label: 'Çok büyük ve çok küçük sayıları bilimsel gösterimle ifade eder ve karşılaştırır', full: 'M.8.1.2.5. Çok büyük ve çok küçük sayıları bilimsel gösterimle ifade eder ve karşılaştırır.' },
    { code: 'M.8.1.3.1.', label: 'Tamkare pozitif tam sayılarla bu sayıların karekökleri arasındaki ilişkiyi belirler', full: 'M.8.1.3.1. Tamkare pozitif tam sayılarla bu sayıların karekökleri arasındaki ilişkiyi belirler.' },
    { code: 'M.8.1.3.2.', label: 'Tam kare olmayan kareköklü bir sayının hangi iki doğal sayı arasında olduğunu belirler', full: 'M.8.1.3.2. Tam kare olmayan kareköklü bir sayının hangi iki doğal sayı arasında olduğunu belirler.' },
    { code: 'M.8.1.3.3.', label: 'Kareköklü bir ifadeyi a√b şeklinde yazar ve a√b şeklindeki ifadede katsayıyı kök içine alır', full: 'M.8.1.3.3. Kareköklü bir ifadeyi a√b şeklinde yazar ve a√b şeklindeki ifadede katsayıyı kök içine alır.' },
    { code: 'M.8.1.3.4.', label: 'Kareköklü ifadelerde çarpma ve bölme işlemlerini yapar', full: 'M.8.1.3.4. Kareköklü ifadelerde çarpma ve bölme işlemlerini yapar.' },
    { code: 'M.8.1.3.5.', label: 'Kareköklü ifadelerde toplama ve çıkarma işlemlerini yapar', full: 'M.8.1.3.5. Kareköklü ifadelerde toplama ve çıkarma işlemlerini yapar.' },
    { code: 'M.8.1.3.6.', label: 'Kareköklü bir ifade ile çarpıldığında, sonucu bir doğal sayı yapan çarpanlara örnek verir', full: 'M.8.1.3.6.Kareköklü bir ifade ile çarpıldığında, sonucu bir doğal sayı yapan çarpanlara örnek verir.' },
    { code: 'M.8.1.3.7.', label: 'Ondalık ifadelerin kareköklerini belirler', full: 'M.8.1.3.7. Ondalık ifadelerin kareköklerini belirler.' },
    { code: 'M.8.1.3.8.', label: 'Gerçek sayıları tanır, rasyonel ve irrasyonel sayılarla ilişkilendirir', full: 'M.8.1.3.8. Gerçek sayıları tanır, rasyonel ve irrasyonel sayılarla ilişkilendirir.' },
    { code: 'M.8.4.1.1.', label: 'En fazla üç veri grubuna ait çizgi ve sütun grafiklerini yorumlar', full: 'M.8.4.1.1.En fazla üç veri grubuna ait çizgi ve sütun grafiklerini yorumlar.' },
    { code: 'M.8.4.1.2.', label: 'Verileri sütun, daire veya çizgi grafiği ile gösterir ve bu gösterimler arasında uygun olan dönüşümleri yapar', full: 'M.8.4.1.2. Verileri sütun, daire veya çizgi grafiği ile gösterir ve bu gösterimler arasında uygun olan dönüşümleri yapar.' },
    { code: 'M.8.5.1.1.', label: 'Bir olaya ait olası durumları belirler', full: 'M.8.5.1.1. Bir olaya ait olası durumları belirler.' },
    { code: 'M.8.5.1.2.', label: '“Daha fazla”, “eşit”, “daha az” olasılıklı olayları ayırt eder, örnek verir', full: 'M.8.5.1.2. “Daha fazla”, “eşit”, “daha az” olasılıklı olayları ayırt eder, örnek verir.' },
    { code: 'M.8.5.1.3.', label: 'Eşit şansa sahip olan olaylarda her bir çıktının olasılık değerinin eşit olduğunu ve bu değerin 1/n olduğunu açıklar', full: 'M.8.5.1.3. Eşit şansa sahip olan olaylarda her bir çıktının olasılık değerinin eşit olduğunu ve bu değerin 1/n olduğunu açıklar.' },
    { code: 'M.8.5.1.4.', label: 'Olasılık değerinin 0 ile 1 arasında (0 ve 1 dâhil) olduğunu anlar', full: 'M.8.5.1.4. Olasılık değerinin 0 ile 1 arasında (0 ve 1 dâhil) olduğunu anlar.' },
    { code: 'M.8.5.1.5.', label: 'Basit bir olayın olma olasılığını hesaplar', full: 'M.8.5.1.5. Basit bir olayın olma olasılığını hesaplar.' },
    { code: 'M.8.2.1.1.', label: 'Basit cebirsel ifadeleri anlar ve farklı biçimlerde yazar', full: 'M.8.2.1.1. Basit cebirsel ifadeleri anlar ve farklı biçimlerde yazar.' },
    { code: 'M.8.2.1.2.', label: 'Cebirsel ifadelerin çarpımını yapar', full: 'M.8.2.1.2. Cebirsel ifadelerin çarpımını yapar.' },
    { code: 'M.8.2.1.3.', label: 'Özdeşlikleri modellerle açıklar', full: 'M.8.2.1.3. Özdeşlikleri modellerle açıklar.' },
    { code: 'M.8.2.1.4.', label: 'Cebirsel ifadeleri çarpanlara ayırır', full: 'M.8.2.1.4. Cebirsel ifadeleri çarpanlara ayırır.' },
    { code: 'M.8.2.2.1.', label: 'Birinci dereceden bir bilinmeyenli denklemleri çözer', full: 'M.8.2.2.1. Birinci dereceden bir bilinmeyenli denklemleri çözer.' },
    { code: 'M.8.2.2.2.', label: 'Koordinat sistemini özellikleriyle tanır ve sıralı ikilileri gösterir', full: 'M.8.2.2.2. Koordinat sistemini özellikleriyle tanır ve sıralı ikilileri gösterir.' },
    { code: 'M.8.2.2.3.', label: 'Aralarında doğrusal ilişki bulunan iki değişkenden birinin diğerine bağlı olarak nasıl değiştiğini tablo ve denklem ile ifade eder', full: 'M.8.2.2.3. Aralarında doğrusal ilişki bulunan iki değişkenden birinin diğerine bağlı olarak nasıl değiştiğini tablo ve denklem ile ifade eder.' },
    { code: 'M.8.2.2.4.', label: 'Doğrusal denklemlerin grafiğini çizer', full: 'M.8.2.2.4. Doğrusal denklemlerin grafiğini çizer.' },
    { code: 'M.8.2.2.5.', label: 'Doğrusal ilişki içeren gerçek hayat durumlarına ait denklem, tablo ve grafiği oluşturur ve yorumlar', full: 'M.8.2.2.5. Doğrusal ilişki içeren gerçek hayat durumlarına ait denklem, tablo ve grafiği oluşturur ve yorumlar.' },
    { code: 'M.8.2.2.6.', label: 'Doğrunun eğimini modellerle açıklar, doğrusal denklemleri ve grafiklerini eğimle ilişkilendirir', full: 'M.8.2.2.6. Doğrunun eğimini modellerle açıklar, doğrusal denklemleri ve grafiklerini eğimle ilişkilendirir.' },
    { code: 'M.8.2.3.1.', label: 'Birinci dereceden bir bilinmeyenli eşitsizlik içeren günlük hayat durumlarına uygun matematik cümleleri yazar', full: 'M.8.2.3.1. Birinci dereceden bir bilinmeyenli eşitsizlik içeren günlük hayat durumlarına uygun matematik cümleleri yazar.' },
    { code: 'M.8.2.3.2.', label: 'Birinci dereceden bir bilinmeyenli eşitsizlikleri sayı doğrusunda gösterir', full: 'M.8.2.3.2. Birinci dereceden bir bilinmeyenli eşitsizlikleri sayı doğrusunda gösterir.' },
    { code: 'M.8.2.3.3.', label: 'Birinci dereceden bir bilinmeyenli eşitsizlikleri çözer', full: 'M.8.2.3.3. Birinci dereceden bir bilinmeyenli eşitsizlikleri çözer.' },
    { code: 'M.8.3.1.1.', label: 'Üçgende kenarortay, açıortay ve yüksekliği inşa eder', full: 'M.8.3.1.1. Üçgende kenarortay, açıortay ve yüksekliği inşa eder.' },
    { code: 'M.8.3.1.2.', label: 'Üçgenin iki kenar uzunluğunun toplamı veya farkı ile üçüncü kenarının uzunluğunu ilişkilendirir', full: 'M.8.3.1.2. Üçgenin iki kenar uzunluğunun toplamı veya farkı ile üçüncü kenarının uzunluğunu ilişkilendirir.' },
    { code: 'M.8.3.1.3.', label: 'Üçgenin kenar uzunlukları ile bu kenarların karşısındaki açıların ölçülerini ilişkilendirir', full: 'M.8.3.1.3. Üçgenin kenar uzunlukları ile bu kenarların karşısındaki açıların ölçülerini ilişkilendirir.' },
    { code: 'M.8.3.1.4.', label: 'Yeterli sayıda elemanının ölçüleri verilen bir üçgeni çizer', full: 'M.8.3.1.4. Yeterli sayıda elemanının ölçüleri verilen bir üçgeni çizer.' },
    { code: 'M.8.3.1.5.', label: 'Pisagor bağıntısını oluşturur, ilgili problemleri çözer', full: 'M.8.3.1.5. Pisagor bağıntısını oluşturur, ilgili problemleri çözer.' },
    { code: 'M.8.3.3.1.', label: 'Eşlik ve benzerliği ilişkilendirir, eş ve benzer şekillerin kenar ve açı ilişkilerini belirler', full: 'M.8.3.3.1. Eşlik ve benzerliği ilişkilendirir, eş ve benzer şekillerin kenar ve açı ilişkilerini belirler.' },
    { code: 'M.8.3.3.2.', label: 'Benzer çokgenlerin benzerlik oranını belirler, bir çokgene eş ve benzer çokgenler oluşturur', full: 'M.8.3.3.2. Benzer çokgenlerin benzerlik oranını belirler, bir çokgene eş ve benzer çokgenler oluşturur' },
    { code: 'M.8.3.2.1.', label: 'Nokta, doğru parçası ve diğer şekillerin öteleme sonucundaki görüntülerini çizer', full: 'M.8.3.2.1. Nokta, doğru parçası ve diğer şekillerin öteleme sonucundaki görüntülerini çizer.' },
    { code: 'M.8.3.2.2.', label: 'Nokta, doğru parçası ve diğer şekillerin yansıma sonucu oluşan görüntüsünü oluşturur', full: 'M.8.3.2.2. Nokta, doğru parçası ve diğer şekillerin yansıma sonucu oluşan görüntüsünü oluşturur.' },
    { code: 'M.8.3.2.3.', label: 'Çokgenlerin öteleme ve yansımalar sonucunda ortaya çıkan görüntüsünü oluşturur', full: 'M.8.3.2.3. Çokgenlerin öteleme ve yansımalar sonucunda ortaya çıkan görüntüsünü oluşturur.' },
    { code: 'M.8.3.4.1.', label: 'Dik prizmaları tanır, temel elemanlarını belirler, inşa eder ve açınımını çizer', full: 'M.8.3.4.1. Dik prizmaları tanır, temel elemanlarını belirler, inşa eder ve açınımını çizer.' },
    { code: 'M.8.3.4.2.', label: 'Dik dairesel silindirin temel elemanlarını belirler, inşa eder ve açınımını çizer', full: 'M.8.3.4.2. Dik dairesel silindirin temel elemanlarını belirler, inşa eder ve açınımını çizer.' },
    { code: 'M.8.3.4.3.', label: 'Dik dairesel silindirin yüzey alanı bağıntısını oluşturur, ilgili problemleri çözer', full: 'M.8.3.4.3. Dik dairesel silindirin yüzey alanı bağıntısını oluşturur, ilgili problemleri çözer.' },
    { code: 'M.8.3.4.4.', label: 'Dik dairesel silindirin hacim bağıntısını oluşturur; ilgili problemleri çözer', full: 'M.8.3.4.4. Dik dairesel silindirin hacim bağıntısını oluşturur; ilgili problemleri çözer.' },
    { code: 'M.8.3.4.5.', label: 'Dik piramidi tanır, temel elemanlarını belirler, inşa eder ve açınımını çizer', full: 'M.8.3.4.5. Dik piramidi tanır, temel elemanlarını belirler, inşa eder ve açınımını çizer.' },
    { code: 'M.8.3.4.6.', label: 'Dik koniyi tanır, temel elemanlarını belirler, inşa eder ve açınımını çizer', full: 'M.8.3.4.6. Dik koniyi tanır, temel elemanlarını belirler, inşa eder ve açınımını çizer.' },
  ],
};
